baseURL = 'https://jaqkofalltrades.com/'
languageCode = 'en-us'
title = 'JAQK of All Trades'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  site_logo = "images\jaqk of all trades v3 small.png" # replaces the site name in the top left corner with a logo image
  commentoEnable = true

[markup]
  [markup.tableOfContents]
    endLevel = 1
    ordered = false
    startLevel = 1

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3